### ISSUE TITLE
Running on Emulator

### ISSUE THREAD

**Issue by 42elenz** [DenisovAV/flutter_gemma#32]
First thank you very much for the example code and your work.

I have multiple questions regarding the repo:

1. Which Kaggle model should I load? The GPU or CPU one?

2. I am getting this Error on an emulated google pixel android x64:

> FATAL EXCEPTION: main
E/AndroidRuntime( 5981): Process: dev.flutterberlin.flutter_gemma_example, PID: 5981
E/AndroidRuntime( 5981): java.lang.UnsatisfiedLinkError: dlopen failed: library "libllm_inference_engine_jni.so" not found
E/AndroidRuntime( 5981):        at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
E/AndroidRuntime( 5981):        at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
E/AndroidRuntime( 5981):        at java.lang.System.loadLibrary(System.java:1661)
E/AndroidRuntime( 5981):        at com.google.mediapipe.tasks.genai.llminference.LlmInference.<clinit>(LlmInference.java:37)
E/AndroidRuntime( 5981):        at dev.flutterberlin.flutter_gemma.InferenceModel.<init>(InferenceModel.kt:66)
E/AndroidRuntime( 5981):        at dev.flutterberlin.flutter_gemma.InferenceModel.<init>(Unknown Source:0)
E/AndroidRuntime( 5981):        at dev.flutterberlin.flutter_gemma.InferenceModel$Companion.getInstance(InferenceModel.kt:98)
E/AndroidRuntime( 5981):        at dev.flutterberlin.flutter_gemma.FlutterGemmaPlugin.onMethodCall(FlutterGemmaPlugin.kt:48)
E/AndroidRuntime( 5981):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime( 5981):        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime( 5981):        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime( 5981):        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 5981):        at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime( 5981):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5981):        at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime( 5981):        at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime( 5981):        at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime( 5981):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5981):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime( 5981):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/Process ( 5981): Sending signal. PID: 5981 SIG: 9
Lost connection to device.

Can someone point me to a solution here? I am a bit lost.

Thank you very much :)

**Comment by DenisovAV** [comment]
Hello, sorry for delayed answer, just holidays.
It should work with CPU and GPU you can try any.
I just checked, everything works fine wyth my emulator, Pixel 7 API 33, Android 13 Tiramisu arm64
Could you share a bit more detail about your emulator? I'll try to reproduce
